pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                ./home/univates/finan/vendor/bin/sail down
                git pull
                ./home/univates/finan/vendor/bin/sail up -d
            }
        }
    }
}
