pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                sh "./home/univates/finan/vendor/bin/sail down"
                sh "git pull"
                sh "./home/univates/finan/vendor/bin/sail up -d"
            }
        }
    }
}
