#!/usr/bin/env groovy
pipeline {
    agent none
    stages {
        stage('PHP 7.4') {
            agent {
            docker {
              image 'php:7.4-cli'
              args '-u root:sudo'
            }
          }
        }
    }
}